---- create Database -----
CREATE DATABASE GITCODE
USE GITCODE

  ------ create table -----
CREATE TABLE STUDENT
(
ID INT,
NAME VARCHAR(50),
CITY VARCHAR (50),
MOB_NO BIGINT,
DEPT VARCHAR(50),
SALARY BIGINT
)

SELECT * FROM STUDENT 

insert into STUDENT values(1,'Vaishnavi','Pune',9373192850,'ENTC',50000)
